export const SUBCATEGORIES = {
  Peluquería: [
    "Corte de cabello",
    "Tinte y coloración",
    "Peinado y estilizado",
    "Barba y afeitado",
    "Tratamientos capilares",
    "Extensiones",
    "Alisado y permanente",
  ],
  Uñas: [
    "Manicure",
    "Pedicure",
    "Uñas acrílicas",
    "Uñas de gel",
    "Nail art",
    "Esmaltado semipermanente",
  ],
  Masajes: [
    "Masaje relajante",
    "Masaje deportivo",
    "Masaje terapéutico",
    "Masaje descontracturante",
    "Reflexología",
    "Masaje prenatal",
  ],
  Plomería: [
    "Reparación de tuberías",
    "Instalación de grifos",
    "Destape de cañerías",
    "Instalación de sanitarios",
    "Reparación de filtraciones",
    "Instalación de calentadores",
    "Mantenimiento de tanques",
  ],
  Electricidad: [
    "Instalación eléctrica",
    "Reparación de circuitos",
    "Instalación de lámparas",
    "Cableado estructurado",
    "Instalación de tomacorrientes",
    "Revisión de tableros",
    "Instalación de plantas eléctricas",
  ],
  Limpieza: [
    "Limpieza de hogar",
    "Limpieza de oficinas",
    "Limpieza de fachadas",
    "Limpieza post obra",
    "Limpieza de alfombras",
    "Desinfección de espacios",
    "Limpieza de vidrios",
  ],
  Pintura: [
    "Pintura de interiores",
    "Pintura de exteriores",
    "Pintura de fachadas",
    "Pintura decorativa",
    "Estuco y resane",
    "Impermeabilización",
  ],
  Mudanzas: [
    "Mudanza residencial",
    "Mudanza empresarial",
    "Embalaje y desembalaje",
    "Transporte de muebles",
    "Montaje y desmontaje",
    "Guardamuebles",
  ],
};
